### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by iamdavidmichaelmoore** [cen4010-fa21-g17/m3-vs-prototype#3]
Child Issues:
Order of Priority:
- [ ] Complete Next.js tutorial & documentation
- [ ] Create sitemap
- [ ] Install Material UI template
- [ ] Create core site UI
